version: '3.8'

services:
  api:
    build: .
    depends_on:
      - redis
      - db
    ports:
      - "8000:80"

  worker:
    build: .
    command: celery -A workers.tasks worker --loglevel=info
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=docking_db